steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      ['-c', 'docker pull gcr.io/$PROJECT_ID/carkee-api-staging:latest || exit 0']
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/carkee-api-staging:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/carkee-api-staging:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'app.staging.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=solveware'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment',
        'carkee-api-staging',
        'carkee-api-staging=gcr.io/$PROJECT_ID/carkee-api-staging:$SHORT_SHA',
      ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=solveware'
images:
  [
    'gcr.io/$PROJECT_ID/carkee-api-staging:$SHORT_SHA',
    'gcr.io/$PROJECT_ID/carkee-api-staging:latest',
  ]
timeout: 900s
options:
  machineType: 'N1_HIGHCPU_8'
