
FROM node:12-alpine
RUN apk update && apk add python make g++ && rm -rf /var/cache/apk/

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . ./

RUN apk del python make g++

EXPOSE 80

CMD ["npm","run","dev"]