module.exports = {
  // SENDGRID_API: process.env.SENDGRID_API_KEY,
  GCLOUD_BUCKET: process.env.GCLOUD_BUCKET,
  GCLOUD_PROEJCT: process.env.GCLOUD_PROJECT,
  GCLOUD_CLIENT_EMAIL: process.env.GCLOUD_CLIENT_EMAIL,
  GCLOUD_PRIVATE_KEY: process.env.GCLOUD_PRIVATE_KEY,
};
