FROM node:lts-alpine as builder
WORKDIR /app

COPY package.json ./
RUN apk update && apk add python make g++ && rm -rf /var/cache/apk/
RUN apk add --no-cache git
RUN npm install
COPY . ./

EXPOSE 3000

CMD ["yarn", "run", "dev"]